// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/03/2025, 21.12.50
const configMerger = require("D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/plugins/**/*.{js,ts,mjs}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/composables/**/*.{js,ts,mjs}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/utils/**/*.{js,ts,mjs}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Cacape/Data Naufal/Informatika/Project/personal-portofolio/app.config.{js,ts,mjs}"] } }));

module.exports = config
